CREATE TABLE projeto (
    id_projeto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    nome_projeto VARCHAR2(250) NOT NULL, 
    tipo_projeto VARCHAR2(20) NOT NULL, 
    CONSTRAINT pk_projeto PRIMARY KEY (id_projeto)
);

CREATE TABLE tipo_painel (
    id_tipo_painel 		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	descricao 			VARCHAR(250) 	NOT NULL,
    CONSTRAINT pk_tipo_painel PRIMARY KEY(id_tipo_painel)
);

CREATE TABLE tipo_painel_projeto (
    id_tipo_painel_projeto 		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_projeto 					NUMBER 	NOT NULL,
    id_tipo_painel 				NUMBER 	NOT NULL,
    CONSTRAINT pk_tipo_painel_projetos PRIMARY KEY (id_tipo_painel_projeto),
    CONSTRAINT fk_projeto_tipo_painel_projeto FOREIGN KEY (id_projeto)
    	REFERENCES projeto (id_projeto),
    CONSTRAINT fk_tipo_painel_projeto FOREIGN KEY (id_tipo_painel)
    	REFERENCES tipo_painel (id_tipo_painel)
);

-- INSERIR PROJETOS --

INSERT INTO projeto (nome_projeto, tipo_projeto) VALUES
    ('Sol do Sertão', 'urbano');
INSERT INTO projeto (nome_projeto, tipo_projeto) VALUES
    ('Cluster de Serra Branca', 'urbano');
INSERT INTO projeto (nome_projeto, tipo_projeto) VALUES
    ('Complexo Solar Serra do Mato', 'urbano');
INSERT INTO projeto (nome_projeto, tipo_projeto) VALUES
    ('Complexo Solar Janaúba', 'urbano');
INSERT INTO projeto (nome_projeto, tipo_projeto) VALUES
    ('Complexo Solar Luzia', 'urbano');
INSERT INTO projeto (nome_projeto, tipo_projeto) VALUES
    ('Complexo Solar Luzia', 'urbano');

SELECT * FROM projeto;

-- INSERIR TIPOS PAINEIS --

INSERT INTO tipo_painel (descricao) VALUES('silício monocristalino');
INSERT INTO tipo_painel (descricao) VALUES('silício policristalino');
INSERT INTO tipo_painel (descricao) VALUES('silício amorfo (a-Si)');
INSERT INTO tipo_painel (descricao) VALUES('telureto de cádmio (CdTe)');
INSERT INTO tipo_painel (descricao) VALUES('seleneto de cobre');
INSERT INTO tipo_painel (descricao) VALUES('fotovoltaicas orgânicas (OPV)');
INSERT INTO tipo_painel (descricao) VALUES('híbrido - HJT');
INSERT INTO tipo_painel (descricao) VALUES('silício amorfo (a-Si)');

SELECT * FROM tipo_painel;

-- INSERIR TIPO PAINEL PROJETO --
INSERT INTO tipo_painel_projeto (id_projeto, id_tipo_painel) VALUES (1, 4);
INSERT INTO tipo_painel_projeto (id_projeto, id_tipo_painel) VALUES (1, 5);
INSERT INTO tipo_painel_projeto (id_projeto, id_tipo_painel) VALUES (2, 6);
INSERT INTO tipo_painel_projeto (id_projeto, id_tipo_painel) VALUES (3, 5);
INSERT INTO tipo_painel_projeto (id_projeto, id_tipo_painel) VALUES (4, 4);
INSERT INTO tipo_painel_projeto (id_projeto, id_tipo_painel) VALUES (2, 4);
INSERT INTO tipo_painel_projeto (id_projeto, id_tipo_painel) VALUES (5, 2);
INSERT INTO tipo_painel_projeto (id_projeto, id_tipo_painel) VALUES (4, 1);
INSERT INTO tipo_painel_projeto (id_projeto, id_tipo_painel) VALUES (3, 3);

SELECT * FROM tipo_painel_projeto;

SELECT nome_projeto "Nome Projeto", tipo_projeto "Tipo Projeto", descricao "Tipo Painel"
    FROM 		tipo_painel_projeto tpp
    INNER JOIN 	projeto p
    ON 			tpp.id_projeto = p.id_projeto
    INNER JOIN 	tipo_painel tp
    ON 			tpp.id_tipo_painel = tp.id_tipo_painel;


CREATE TABLE tecnico (
    id_tecnico 		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    nome_tecnico 	VARCHAR2(50) 	NOT NULL, 
    cpf 			VARCHAR2(11) 	NOT NULL, 
    contato 		VARCHAR2(11) 	NOT NULL,
    id_projeto 		NUMBER 			NOT NULL,
    CONSTRAINT pk_tecnico PRIMARY KEY (id_tecnico), 
    CONSTRAINT fk_projeto_tecnico FOREIGN KEY (id_projeto)
        REFERENCES projeto (id_projeto)
);

CREATE TABLE projeto_tecnico (
    id_projeto_tecnico 		NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_projeto 				NUMBER 	NOT NULL,
    id_tecnico				NUMBER 	NOT NULL,
    CONSTRAINT pk_projeto_tecnico PRIMARY KEY (id_projeto_tecnico),
    CONSTRAINT fk_tecnico_tecnico FOREIGN KEY (id_tecnico)
    	REFERENCES tecnico (id_tecnico),
    CONSTRAINT fk_projeto_projeto_tecnico FOREIGN KEY (id_projeto)
    	REFERENCES projeto (id_projeto)
);

INSERT INTO tecnico (nome_tecnico, cpf, contato, id_projeto) VALUES 
    ('Karen Bastos', 63288313405, 31988887777,3);
INSERT INTO tecnico (nome_tecnico, cpf, contato, id_projeto) VALUES 
    ('João Pedro', 60228454166, 11987787871,4);
INSERT INTO tecnico (nome_tecnico, cpf, contato, id_projeto) VALUES 
    ('Luiz Fernando', 29569615869, 21987676787,1);
INSERT INTO tecnico (nome_tecnico, cpf, contato, id_projeto) VALUES 
    ('Julia Lima', 33638473430, 33988665757,2);
INSERT INTO tecnico (nome_tecnico, cpf, contato, id_projeto) VALUES 
    ('Ana Maria', 97618982376, 31987576677,5);
INSERT INTO tecnico (nome_tecnico, cpf, contato, id_projeto) VALUES 
    ('Pedro Lucas', 33181047791, 11985454687,6);

SELECT * FROM tecnico;

SELECT * FROM projeto_tecnico; --ERRO VERIFICAR!!! ---
SELECT * FROM projeto;
SELECT * FROM tecnico;


